services:
  chat-front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: chat-front
    attach: false
    depends_on:
      - chat-back
  chat-back:
    build:
      context: ../chat-backend/
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    stdin_open: true
    tty: true
    container_name: chat-back
    attach: false
    restart: unless-stopped
