import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from '@/context/themeProvider'
import ToggleTheme from './components/ToggleTheme'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--poppins-font',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToggleTheme />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
